version: "3"

services:
  app:
    build:
      context: .
    environment:
      MONGODB_USERNAME: "${MONGODB_USERNAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MONGODB_HOST: "mongo"
    ports:
      - "30000:3000"

  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: npm-checker
    ports:
      - "27017:27017"
